# Generated by Django 5.2.5 on 2025-10-11 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_86ea8b_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='content_type',
            new_name='target_content_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='object_id',
            new_name='target_object_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(max_length=255),
        ),
    ]
